from __future__ import annotations

import argparse
import json
from pathlib import Path
import signal
import sys
from typing import Any

from . import __version__
from .config import ConfigError, load_config
from .core import InstallerError
from .orchestrator import Installer


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="nomosmart-install",
        description="Guided, resumable NomoSmart Kubernetes installer",
    )
    parser.add_argument("--version", action="version", version=__version__)
    commands = parser.add_subparsers(dest="command", required=True)
    for name in (
        "plan",
        "install",
        "resume",
        "status",
        "verify",
        "finalize",
        "doctor",
    ):
        command = commands.add_parser(name)
        command.add_argument(
            "--config",
            required=True,
            type=Path,
            help="versioned non-secret installer TOML",
        )
    reset_plan = commands.add_parser("reset-plan")
    reset_plan.add_argument("--config", required=True, type=Path)
    reset_plan.add_argument(
        "--output",
        required=True,
        type=Path,
        help="new owner-only reset plan JSON path",
    )
    reset_apply = commands.add_parser("reset-apply")
    reset_apply.add_argument("--config", required=True, type=Path)
    reset_apply.add_argument(
        "--plan",
        required=True,
        type=Path,
        help="owner-only reset plan generated by reset-plan",
    )
    reset_apply.add_argument(
        "--confirm",
        required=True,
        help="exact reset plan digest",
    )
    factory_plan = commands.add_parser("factory-plan")
    factory_plan.add_argument("--config", required=True, type=Path)
    factory_plan.add_argument(
        "--output",
        required=True,
        type=Path,
        help="new owner-only CHG-252 factory inventory JSON path",
    )
    factory_apply = commands.add_parser("factory-apply")
    factory_apply.add_argument("--config", required=True, type=Path)
    factory_apply.add_argument(
        "--plan",
        required=True,
        type=Path,
        help="owner-only plan generated by factory-plan",
    )
    factory_apply.add_argument(
        "--confirm",
        required=True,
        help="exact factory plan digest",
    )
    factory_apply.add_argument(
        "--approval",
        required=True,
        help="exact plan-bound permanent-delete approval phrase",
    )
    return parser


def _emit(payload: dict[str, Any], *, stream: Any = sys.stdout) -> None:
    print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True), file=stream)


def main(argv: list[str] | None = None) -> int:
    installer: Installer | None = None

    def terminate(
        signum: int,
        _frame: object,
    ) -> None:
        if installer is not None:
            installer.runner.forward_signal(signum)
        raise KeyboardInterrupt

    signal.signal(signal.SIGINT, terminate)
    signal.signal(signal.SIGTERM, terminate)
    args = _parser().parse_args(argv)
    try:
        installer = Installer(load_config(args.config))
        if args.command == "reset-plan":
            result = installer.reset_plan(args.output)
        elif args.command == "reset-apply":
            result = installer.reset_apply(
                args.plan, confirmation=args.confirm
            )
        elif args.command == "factory-plan":
            result = installer.factory_plan(args.output)
        elif args.command == "factory-apply":
            result = installer.factory_apply(
                args.plan,
                confirmation=args.confirm,
                approval=args.approval,
            )
        else:
            operation = getattr(installer, args.command)
            result = operation()
        _emit(result)
        return 0
    except (ConfigError, InstallerError) as exc:
        exit_code = exc.exit_code if isinstance(exc, InstallerError) else 20
        payload: dict[str, Any] = {
            "status": (
                "action-required"
                if exit_code == 10
                else "failed"
            ),
            "failure_class": type(exc).__name__,
            "detail": str(exc),
            "exit_code": exit_code,
            "next_safe_command": (
                f"nomosmart-install resume --config {args.config}"
                if isinstance(exc, InstallerError)
                else f"nomosmart-install plan --config {args.config}"
            ),
        }
        if installer is not None and isinstance(exc, InstallerError):
            try:
                progress = installer.status()
                payload["current_stage"] = progress.get("current_stage")
                payload["completed_stages"] = progress.get(
                    "completed_stages", []
                )
            except InstallerError:
                pass
        _emit(payload, stream=sys.stderr)
        return exit_code
    except KeyboardInterrupt:
        _emit(
            {
                "status": "interrupted",
                "failure_class": "KeyboardInterrupt",
                "detail": "installer interrupted; rerun resume",
                "exit_code": 30,
            },
            stream=sys.stderr,
        )
        return 30
    except Exception:
        _emit(
            {
                "status": "failed",
                "failure_class": "UnexpectedInstallerFailure",
                "detail": "installer failed without exposing protected command output",
                "exit_code": 30,
                "next_safe_command": (
                    f"nomosmart-install status --config {args.config}"
                ),
            },
            stream=sys.stderr,
        )
        return 30


if __name__ == "__main__":
    raise SystemExit(main())
