import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("chat answers use shared safe markdown rendering without html injection", async () => {
  const safeMarkdown = await readFile(new URL("../src/components/SafeMarkdown.tsx", import.meta.url), "utf8");
  const documentChat = await readFile(new URL("../src/app/project/[id]/knowledge/[knowledgeId]/chat-test/page.tsx", import.meta.url), "utf8");
  const knowledgeDetail = await readFile(new URL("../src/app/project/[id]/knowledge/[knowledgeId]/page.tsx", import.meta.url), "utf8");
  const chunkMarkdown = await readFile(new URL("../src/components/ChunkMarkdownView.tsx", import.meta.url), "utf8");
  const projectChat = await readFile(new URL("../src/components/ProjectChatTest.tsx", import.meta.url), "utf8");
  const chatEvidence = await readFile(new URL("../src/components/ChatResponseEvidence.tsx", import.meta.url), "utf8");
  const documentLayoutViewer = await readFile(new URL("../src/components/DocumentLayoutViewer.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../src/app/globals.css", import.meta.url), "utf8");

  assert.match(safeMarkdown, /export function SafeMarkdown/);
  assert.match(safeMarkdown, /export function SafeMarkdownInline/);
  assert.match(safeMarkdown, /import ReactMarkdown/);
  assert.match(safeMarkdown, /import remarkGfm/);
  assert.match(safeMarkdown, /remarkNomoSmart/);
  assert.match(safeMarkdown, /skipHtml/);
  assert.match(safeMarkdown, /SAFE_ABSOLUTE_SCHEMES/);
  assert.match(safeMarkdown, /safe-markdown-table-wrapper/);
  assert.match(safeMarkdown, /safe-markdown-table/);
  assert.match(safeMarkdown, /safe-markdown-citation/);
  assert.match(safeMarkdown, /hProperties: \{ \.\.\.\(item\.data\?\.hProperties \?\? \{\}\), value: ordinal \}/);
  assert.doesNotMatch(safeMarkdown, /dangerouslySetInnerHTML/);
  assert.match(documentChat, /import \{ ChatResponseEvidence \}/);
  assert.match(knowledgeDetail, /import \{ DocumentLayoutViewer \}/);
  assert.match(projectChat, /import \{ ChatResponseEvidence \}/);
  assert.match(chatEvidence, /import \{ SafeMarkdown \}/);
  assert.match(chatEvidence, /ChunkMarkdownView/);
  assert.match(chatEvidence, /answerFallback/);
  assert.match(chatEvidence, /onCitationSelect=\{openCitation\}/);
  assert.match(knowledgeDetail, /<DocumentLayoutViewer/);
  assert.match(documentLayoutViewer, /function LayoutBlockView/);
  assert.match(documentLayoutViewer, /const inlineSource = block\.inline_markdown \|\| blockText/);
  assert.match(documentLayoutViewer, /SafeMarkdownInline source=\{inlineSource\}/);
  assert.match(documentLayoutViewer, /item\.inline_markdown \|\| item\.text/);
  assert.match(documentLayoutViewer, /block\.table_header/);
  assert.match(documentLayoutViewer, /"data-continuation-index": block\.continuation_index/);
  assert.match(knowledgeDetail, /return <SafeMarkdown className="rendered-markdown-document" source=\{source\} \/>/);
  assert.match(knowledgeDetail, /<ChunkMarkdownView/);
  assert.match(chunkMarkdown, /display_markdown/);
  assert.match(chunkMarkdown, /markdown_content/);
  assert.match(chunkMarkdown, /kind: "content"/);
  assert.doesNotMatch(chunkMarkdown, /retrieval_text/);
  assert.match(documentChat, /answerFallback=\{t\("documentChatNoVerifiableAnswer"\)\}/);
  assert.match(projectChat, /answerFallback=\{t\("projectChatNoBackendAnswer"\)\}/);
  assert.match(styles, /\.safe-markdown/);
  assert.match(styles, /\.chunk-card \.safe-markdown/);
  assert.match(styles, /\.safe-markdown-table-wrapper/);
  assert.match(styles, /\.safe-markdown-table/);
  assert.match(styles, /\.safe-markdown-citation/);
  assert.match(styles, /\.safe-markdown-semantic-code/);
  assert.match(styles, /\.safe-markdown-semantic-strong/);
});
